#!/bin/sh -e
#
# recovery usb
if [ -f /media/usb/update.zip ]; then
  unzip /media/usb/update.zip -d /home/pi/
  bash /home/pi/_update
  exit 0
fi

# hostname management
rpi_serial=$(grep "Serial" /proc/cpuinfo | awk '{print $3}' | rev | cut -c -8 | rev)
if [ $rpi_serial != "$(hostname)" ]
then
  hostnamectl set-hostname --static ${rpi_serial}
  echo "127.0.0.1 localhost" > /etc/hosts
  echo "::1       localhost ip6-localhost ip6-loopback" >> /etc/hosts
  echo "ff02::1   ip6-allnodes" >> /etc/hosts
  echo "ff02::2   ip6-allrouters" >> /etc/hosts
  echo "127.0.0.1 ${rpi_serial}" >> /etc/hosts
  shutdown -r now
fi

mkdir -p /home/pi/code
mkdir -p /home/pi/myimage
mkdir -p /home/pi/myaudio
mkdir -p /home/pi/mymodel

# ap start
/home/pi/openpibo-os/system/wifi-ap-sta run

# network init
python3 /home/pi/openpibo-os/system/booting.py &

# run server
cd /home/pi/openpibo-os/ide;node main.js &
cd /home/pi/openpibo-os/tools;python3 main.py &

# motor init
#servo init

# ap start
#/home/pi/openpibo-os/system/wifi-ap-sta run

# Amp init
#gpio mode 7 out
#gpio write 7 1

# pir on
#echo "#30:on!" > /dev/ttyS0

iw wlan0 set power_save off
iw ap0 set power_save off
exit 0
